spring:
  application:
    name: embedded-kafka
  kafka:
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092


